имя: CI

на:
# События, которые запускают
толкать:
ветки: [ "главная" ]
pull_request:
ветки: [ "главная" ]

# jobs запускаются параллельно, если не указана последовательность
Вакансии:
# Название job вы можете назвать как угодно
my_build_job:
# Операционная система в виртуальной машине, в которой запускаются процессы
выполняется: ubuntu-последняя версия
шаги:
# Actions от Github: проверяет гит, репозитарий и т.д.
- использует: действие/проверка@v3

# Устанавоиваем все необходимые зависимости и запскаем тесты node
- название: установка, тестирование и сборка
выполнить: 
при install
при run build
# Пример однолинейного простого скрипта shell
- имя: запустить однострочный скрипт
выполнить: echo Привет, мир!

# Пример многолинейного скрипта shell
- имя: запустить многострочный скрипт
выполнить: 
echo добавляет другие действия для сборки,
протестируйте echo и разверните свой проект.

- имя: запустить js-файл для тестирования
выполнить: узел js/script.js 
